# Generated by Django 2.2.4 on 2019-08-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codereviewerapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
